- name: "create mysql-slave"
  docker_container:
     name: mysql-slave
     image: mysql:5.7
     networks:
        - name: "mysql-cluster"
     env:
       MYSQL_ROOT_PASSWORD=root
     volumes:
       - ./data/mysql-slave:/var/lib/mysql/
       - ./config/mysql-slave:/etc/mysql/conf.d/
     state: started
  tags: mysql-slave
